package br.com.unip.carrinho.exception

enum class ECodigoErro {

    ERRO_INESPERADO("000"),
    TOKEN_EXPIRADO("001"),
    TOKEN_INVALIDO("002"),
    CONEXAO_RECUSADA("003"),
    ACESSO_NEGADO("004"),
    CAMPO_OBRIGATORIO("005"),
    PARAMETRO_INVALIDO("006"),
    CAMPO_DEVE_SER_NUMERICO("007"),
    PEDIDO_NAO_ENCONTRADO("008"),
    FORMATO_DATA_INVALIDO("009"),
    PRODUTO_NAO_ENCONTRADO("010"),
    ID_PRODUTO_OBRIGATORIO("011"),
    CAMPO_VALOR_DEVE_SER_NUMERICO("012"),
    CAMPO_VALOR_OBRIGATORIO("013"),
    CAMPO_DESCRICAO_OBRIGATORIO("014"),
    CAMPO_NOME_OBRIGATORIO("015"),
    CLIENTE_JA_POSSUI_UM_CARRINHO("016"),
    CARRINHO_NAO_ENCONTRADO("017"),
    CARRINHO_POSSUI_PRODUTOS_DE_OUTRO_FORNECEDOR("018"),
    CARDAPIO_NAO_ENCONTRADO("019"),
    DATA_NAO_DEVE_SER_RETROATIVA("020");

    val codigo: String

    constructor(codigo: String) {
        this.codigo = codigo
    }
}